### ISSUE TITLE
Support arm7/aarch64 on self hosted runners

### ISSUE THREAD

**Issue by paresy** [mathieu-bour/setup-sentry-cli#11]
sentry-cli also provides binaries for those architectures. It would be awesome if this action could also download it if required.

See: https://sentry.io/get-cli

Thanks for looking into it!

**Comment by matbour** [comment]
Thanks for the feature request. I will **try** to implement this feature, but I do not have any runner running on this architecture at my disposition so I'll try to implement this feature blindly.
When it will be ready, could you possibly test the feature for your use case?

**Comment by paresy** [comment]
Sure. If you have a feature branch ready ping me and i'll give it a spin!

Thanks!

**Comment by matbour** [comment]
Could you possibly try using this following branch?

```yaml
- uses: mathieu-bour/setup-sentry-cli@feat/amdv7-arch
```

**Comment by paresy** [comment]
It works on ARMv7 (32Bit), but it probably won't work on ARM64 (aarch64) yet. At least i haven't seen a code-path in the PR for it yet. Is that right? I will run an ARM64 build tomorrow and give you "tested" results. Thanks for the quick patch so far!

(This link is still missing as far as i have seen: SENTRY_DOWNLOAD_Linux_aarch64="https://downloads.sentry-cdn.com/sentry-cli/1.64.2/sentry-cli-Linux-aarch64")

**Comment by matbour** [comment]
Ok, I was not aware of the ARM versions, etc. I'll define the conditional links for this architecture too.

**Comment by matbour** [comment]
The code should be good by now. You can check the integration of the multiple platform/architectures here:

https://github.com/mathieu-bour/setup-sentry-cli/blob/ccfef2f4a7bf746ea4defdd0aa98ded4b6566657/src/get-download-link.ts#L4-L13

If you get working results, I'll merge the branch into main and publish version 1.2.0.

**Comment by paresy** [comment]
Just wanted to give feedback that i have successfully tested ARMv7 and ARM64 using the feature branch. Great work. Thanks!

**Comment by matbour** [comment]
Thank you very much for your feedback. I'll merge the branch and release version 1.2.0. Consider dropping a star!
