### ISSUE TITLE
Upgrade to Node 16 actions

### ISSUE THREAD

**Issue by njakob** [mathieu-bour/setup-sentry-cli#15]
Heyy!

First of all, thank you for this action!

GitHub deprecated the usage of Node 12 actions and I'm currently getting the following warnings while using the action:

```
Node.js 12 actions are deprecated.
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: mathieu-bour/setup-sentry-cli
```

Therefore, it would be great to upgrade the setup!

**Comment by matbour** [comment]
Correct. Will do ASAP!
Edit: done!

**Comment by njakob** [comment]
Thank you for tackling it this fast @mathieu-bour, all warnings has been addressed :tada:
