### ISSUE TITLE
version: latest seems to use most recent release instead of latest release

### ISSUE THREAD

**Issue by maxkosty** [mathieu-bour/setup-sentry-cli#17]
Hey Mathieu, thanks for creating this super useful action.

Most recent release is sometimes a backport (e.g. right now it's [1.75.1](https://github.com/getsentry/sentry-cli/releases/tag/1.75.1)) which will break workflow that was using 2.x

switching to `version: 2.17.4` which is `Latest` at the time of writing fixed my broken workflow which leads me to believe that using `1.75.1` is the root cause.

<img width="1136" alt="Screenshot 2023-04-27 at 1 40 57 PM" src="https://user-images.githubusercontent.com/490201/234985709-365f1bc6-dddc-4d7b-9c35-e7c3d12a5987.png">

**Comment by matbour** [comment]
That you very much for you report. If I understand correctly, you mean that the release tagged `latest` is sometimes a back of a v1.x instead of a v2.x?

For example, sometimes the version v1.x.y can be considered as `latest` instead of the latest v2?

**Comment by maxkosty** [comment]
yes, that is my understanding...
even though this time `latest` is actually correct (see screenshot and
link) and my suspicion is that `setup-sentry-cli` actually picked 1.7.x
(presumably as _chronologically_ latest) because my workflow broke and
explicitly setting version to `2.whatever` fixed it immediately

**Comment by maxkosty** [comment]
Right now https://github.com/getsentry/sentry-cli/releases/latest redirects
to `2.17.5` but it seems like setup-sentry-cli when used with `version:
latest` actually picked up 1.75.x

**Comment by matbour** [comment]
Thanks for the report and investigation. However, I do think that using the `latest` tag has not the same meaning as the `highest` version. For this reason I am not sure that I should change how the `latest` tag works.

Maybe instead I introduce should semver matching like:

```
version: 2.x
```

**Comment by micahbf** [comment]
I just ran into this issue as well, and setting an explicit `version` will work, but it was very surprising behavior to me, and took me a bit of debugging to track down why our build suddenly stopped working. I was searching the sentry-cli changelog for new breaking changes.

I think people generally understand `latest` to mean `highest`.

**Comment by maxkosty** [comment]
@mathieu-bour Whether or not `latest` means `highest` or not, practically speaking the following happens:
1. new users configures action to use `latest` as a sensible default
2. at the time of setting up the workflow `latest` resolves to `2.x`
3. everything works
4. until one day Sentry publishes a `1.x` backport and marks it as **"Latest"**
5. things break

Example, just a few days ago on Nov 3, 2023 we've released `1.76.0` and labled 
<img width="192" alt="Screenshot 2023-11-06 at 4 34 56 PM" src="https://github.com/mathieu-bour/setup-sentry-cli/assets/490201/80efac9e-7550-475a-895c-cc89330fbfe5">

When it last happened for me I just froze the major version to `2.17.4` to avoid this happening again, but I think a lot of people are affected. 

I'm wondering if it's really on Sentry to not label backports as "Latest" and not the problem with this GH Action. When I initially opened the ticket I wasn't clear if you picked up what Sentry labeled as Latest or simply chronologically most recent.

**Comment by maxkosty** [comment]
Sentry will be fixing this on our side: https://github.com/getsentry/craft/issues/498
My understanding is that once implemented this will ensure that only v2 releases are labeled as "Latest"

**Comment by mydea** [comment]
Just chiming in here, we have already fixed the problem where in our release registry `latest` will not be overwritten if we release a backported v1 version of sentry-cli. So this problem specifically should be gone now!

The problem that we are currently fixing is to ensure the release on github is not marked as "latest". However, that should not really affect anything, except that it is potentially confusing. So I think this can be closed now, as as far as I can see this repo only relies on `downloads.sentry-cdn.com/sentry-cli/latest`, which _should_ be working already as expected even if we release a v1 version. (fixed in https://github.com/getsentry/craft/pull/483)

**Comment by matbour** [comment]
Hi all, thanks for the update. Feel free to re-open if Sentry messes again with the `latest` tag.
