### ISSUE TITLE
when the new version of mapping.txt remains unchanged, it will not be uploaded, resulting in a stack parsing failure

### ISSUE THREAD

**Issue by jiagengArctuition** [mathieu-bour/setup-sentry-cli#19]
for more details, please refer to this issue: https://github.com/getsentry/sentry-java/issues/3132

Sentry's official response indicates that it is an issue with 'mathieu-bour/setup-sentry-cli'

**Comment by matbour** [comment]
To be honest, I don't see how your problem can be related to this repo. I just checked your original issue and it seems that your issue has been solved.

I will close this issue, but feel free to re-open if necessary!
