### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by ijc** [mathieu-bour/setup-sentry-cli#20]
[GitHub has deprecated the usage of Node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/):
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: mathieu-bour/setup-sentry-cli@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Please would you upgrade.

Thanks for providing this action.

**Comment by matbour** [comment]
On it!

**Comment by ijc** [comment]
Thanks, it works great!
